#!/bin/bash

DIR="$HOME/comp-206"

if [ ! -d "$DIR/homework" ]; then
	echo "ERROR: $DIR/homework directory does not exist"
	exit 1
fi

mkdir -p "$DIR/backups"

timestamp=$(date +"%Y-%m-%dT%H:%M:%S")
archive="$DIR/backups/homework-$timestamp.tar.gz"

tar -czvf "$archive" "$DIR/homework"

echo "Created backup: $archive"

